### ISSUE TITLE
Lowercase tags and attributes

### ISSUE THREAD

**Issue by codemonstur** [HtmlUnit/htmlunit-neko#4]
CyberNeko has a feature where it can convert HTML tags and attributes to lower case using a configuration setting.
```
parser.setProperty("http://cyberneko.org/html/properties/names/elems", "lower");
```
This feature was still available in version 2.25 but the current version of 2.36.0 throws an exception when you try to use it.
```
org.xml.sax.SAXNotRecognizedException: Property 'http://cyberneko.org/html/properties/names/elems' is not recognized.
	at org.apache.xerces.parsers.DOMParser.setProperty(Unknown Source)
```
Has it been renamed? Deleted? Is there an alternative way of doing this?
I can't find any documentation.

**Comment by rbri** [comment]
This was deleted for version 2.35.0 because HtmlUnit no longer use this feature (because the browsers are no longer doing this normalization).

Do you have a special case where you need this?

**Comment by codemonstur** [comment]
I have a project called HtmlCompiler (https://github.com/codemonstur/HTMLCompiler). It basically provides frontend features at compile time for a maven project.

One of the features it has is to convert all HTML tags and attributes to lowercase. I have two other versions of Neko which provide this feature out of the box, I also have Jsoup as a parser which does the same. HtmlUnit-neko currently doesn't.

I was hoping it had just been renamed so it would be easy to recreate. 

To answer your question; no I don't strictly-speaking need it, I could write it myself and may have to go in that direction eventually anyway.

**Comment by rbri** [comment]
Am 24. Dezember 2019 11:48:40 MEZ schrieb codemonstur <notifications@github.com>:
>I have a project called HtmlCompiler
>(https://github.com/codemonstur/HTMLCompiler). It basically provides
>frontend features at compile time for a maven project.
>
>One of the features it has is to convert all HTML tags and attributes
>to lowercase. I have two other versions of Neko which provide this
>feature out of the box, I also have Jsoup as a parser which does the
>same. HtmlUnit-neko currently doesn't.
>
>I was hoping it had just been renamed so it would be easy to recreate. 
>
>To answer your question; no I don't strictly-speaking need it, I could
>write it myself and may have to go in that direction eventually anyway.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/HtmlUnit/htmlunit-neko/issues/4#issuecomment-568722199

If you Luke i can Saxophon bring it back

**Comment by codemonstur** [comment]
It would be nice if you could bring it back :)

**Comment by rbri** [comment]
The feature is back, please check with neko-htmlunit-2.37.0-SNAPSHOT

**Comment by codemonstur** [comment]
mvn clean install returns this error for me:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:jar (default) on project neko-htmlunit: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
[ERROR] javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
[ERROR] /home/jurgen/private/projects-to-sort/htmlunit-neko/src/main/java/net/sourceforge/htmlunit/cyberneko/HTMLTagBalancingListener.java:24: error: tag not supported in the generated HTML version: font
[ERROR] * <font style="color: red">EXPERIMENTAL: may change in next release</font><br>
[ERROR] ^
[ERROR] /home/jurgen/private/projects-to-sort/htmlunit-neko/src/main/java/net/sourceforge/htmlunit/cyberneko/HTMLConfiguration.java:262: error: tag not supported in the generated HTML version: font
[ERROR] * <font style="color: red">EXPERIMENTAL: may change in next release</font><br>
[ERROR] ^
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/jdk-13/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/jurgen/private/projects-to-sort/htmlunit-neko/target/apidocs' dir.
[ERROR] -> [Help 1]
```

**Comment by rbri** [comment]
Please try again

**Comment by codemonstur** [comment]
Pulled the changed and ran `mvn -e clean install` this time:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:jar (default) on project neko-htmlunit: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
[ERROR] javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/jdk-13/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/jurgen/private/projects-to-sort/htmlunit-neko/target/apidocs' dir.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:jar (default) on project neko-htmlunit: MavenReportException: Error while generating Javadoc: 
Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.

Command line was: /usr/lib/jvm/jdk-13/bin/javadoc @options @packages

Refer to the generated Javadoc files in '/home/jurgen/private/projects-to-sort/htmlunit-neko/target/apidocs' dir.

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: MavenReportException: Error while generating Javadoc: 
Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.

Command line was: /usr/lib/jvm/jdk-13/bin/javadoc @options @packages

Refer to the generated Javadoc files in '/home/jurgen/private/projects-to-sort/htmlunit-neko/target/apidocs' dir.

	at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.failOnError(AbstractJavadocMojo.java:6715)
	at org.apache.maven.plugins.javadoc.JavadocJar.doExecute(JavadocJar.java:193)
	at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.execute(AbstractJavadocMojo.java:1911)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.maven.reporting.MavenReportException: 
Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.

Command line was: /usr/lib/jvm/jdk-13/bin/javadoc @options @packages

Refer to the generated Javadoc files in '/home/jurgen/private/projects-to-sort/htmlunit-neko/target/apidocs' dir.

	at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.executeJavadocCommandLine(AbstractJavadocMojo.java:5763)
	at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.executeReport(AbstractJavadocMojo.java:2152)
	at org.apache.maven.plugins.javadoc.JavadocJar.doExecute(JavadocJar.java:189)
	... 23 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by rbri** [comment]
Sorry, i'm using jdk 1.8 for all the dev and build.

Can you please try to add 
<source>1.8</source>
to the config of the javadoc plugin

**Comment by codemonstur** [comment]
It works! Ran the unit tests on the HtmlCompiler and the uppercase test now passes. :)

To make `mvn clean install` work I added these lines to the properties tag of the pom:
```
<maven.compiler.source>8</maven.compiler.source>
<maven.compiler.target>8</maven.compiler.target>
<maven.compiler.release>8</maven.compiler.release>
```
And removed these lines from the maven compiler plugin:
```
<configuration>
    <source>1.8</source>
    <target>1.8</target>
</configuration>
```

**Comment by rbri** [comment]
<maven.compiler.release>8</maven.compiler.release> seems to be invalid with jdk 18
can you please try without this line

**Comment by codemonstur** [comment]
I don't have Java 8 installed and I don't want to install it just to test this one out. The release option was added in Java 9 so my guess is that there is no setting you can use to make the pom work with jdk8 AND jdk13.

The problem is only a javadoc issue anyway, the code works fine. And I'm sure it works fine no matter which jdk you use to build it.

Its up to you what you want to do but I'd just release it.

**Comment by rbri** [comment]
But this release setting is required for your jdk to make the maven build worl?

**Comment by codemonstur** [comment]
Yes. Its basically telling jdk13 to pretend it is 8.

**Comment by codemonstur** [comment]
Will there be a new release with this feature?

**Comment by rbri** [comment]
So far there is only the latest snapshot build. But  i plan a release for this weekend.
